version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-custom:v0.0.1
    # hostname: '0.0.0.0'
    container_name: go-development
    # links:
    #   - "mysql"
    #   - "redis"
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - .:/go/src
      # - ./bin:/go/bin